# Generated by Django 4.2.2 on 2023-06-11 20:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0005_remove_document_uploaded_at_document_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
