# Generated by Django 4.2.2 on 2023-06-11 20:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file_manager', '0006_alter_document_document'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Library',
            new_name='Picture',
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
