# Generated by Django 4.2.2 on 2023-06-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0007_rename_library_picture_alter_document_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='description',
        ),
        migrations.AlterField(
            model_name='picture',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
