# Generated by Django 4.2.2 on 2023-06-13 13:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0008_remove_picture_description_alter_picture_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
