# Generated by Django 4.2 on 2023-06-17 16:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0005_file_user_alter_file_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="contacts",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="file",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="email",
            field=models.EmailField(default="example@email.com", max_length=254),
        ),
    ]
