# Generated by Django 4.2.2 on 2023-06-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_contacts_created_at_file_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.EmailField(default='example@email.com', max_length=254),
        ),
    ]
