# Generated by Django 4.2.2 on 2023-06-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_contacts_created_at_file_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='file',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
