# Generated by Django 4.2 on 2023-06-18 10:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0007_remove_contacts_created_at_remove_file_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contacts",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="file",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="email",
            field=models.EmailField(default="example@email.com", max_length=254),
        ),
    ]
