# Generated by Django 4.2 on 2023-06-18 14:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0007_alter_contacts_email"),
        ("contacts", "0008_contacts_created_at_file_created_at_and_more"),
    ]

    operations = []
